package net.pupp.musicdiscsplus.item;

import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.pupp.musicdiscsplus.MusicDiscsPlus;
import net.minecraft.util.Rarity;


public class ItemGenerator {

    private static final Item.Settings DISC_SETTINGS = new Item.Settings().maxCount(1).group(MusicDiscsPlus.DISCS).rarity(Rarity.RARE).maxCount(1);

    public static final Item DISC_001 = registerItem("disc_001", new mdpDiscs(14, musicDiscsPlusSE.DISC_001, DISC_SETTINGS));
    public static final Item DISC_002 = registerItem("disc_002", new mdpDiscs(14, musicDiscsPlusSE.DISC_002, DISC_SETTINGS));
    public static final Item DISC_003 = registerItem("disc_003", new mdpDiscs(14, musicDiscsPlusSE.DISC_003, DISC_SETTINGS));
    public static final Item DISC_004 = registerItem("disc_004", new mdpDiscs(14, musicDiscsPlusSE.DISC_004, DISC_SETTINGS));
    public static final Item DISC_005 = registerItem("disc_005", new mdpDiscs(14, musicDiscsPlusSE.DISC_005, DISC_SETTINGS));
    public static final Item DISC_006 = registerItem("disc_006", new mdpDiscs(14, musicDiscsPlusSE.DISC_006, DISC_SETTINGS));
    public static final Item DISC_007 = registerItem("disc_007", new mdpDiscs(14, musicDiscsPlusSE.DISC_007, DISC_SETTINGS));
    public static final Item DISC_008 = registerItem("disc_008", new mdpDiscs(14, musicDiscsPlusSE.DISC_008, DISC_SETTINGS));
    public static final Item DISC_009 = registerItem("disc_009", new mdpDiscs(14, musicDiscsPlusSE.DISC_009, DISC_SETTINGS));
    public static final Item DISC_010 = registerItem("disc_010", new mdpDiscs(14, musicDiscsPlusSE.DISC_010, DISC_SETTINGS));
    public static final Item DISC_011 = registerItem("disc_011", new mdpDiscs(14, musicDiscsPlusSE.DISC_011, DISC_SETTINGS));
    public static final Item DISC_012 = registerItem("disc_012", new mdpDiscs(14, musicDiscsPlusSE.DISC_012, DISC_SETTINGS));
    public static final Item DISC_013 = registerItem("disc_013", new mdpDiscs(14, musicDiscsPlusSE.DISC_013, DISC_SETTINGS));
    public static final Item DISC_014 = registerItem("disc_014", new mdpDiscs(14, musicDiscsPlusSE.DISC_014, DISC_SETTINGS));
    public static final Item DISC_015 = registerItem("disc_015", new mdpDiscs(14, musicDiscsPlusSE.DISC_015, DISC_SETTINGS));
    public static final Item DISC_016 = registerItem("disc_016", new mdpDiscs(14, musicDiscsPlusSE.DISC_016, DISC_SETTINGS));
    public static final Item DISC_017 = registerItem("disc_017", new mdpDiscs(14, musicDiscsPlusSE.DISC_017, DISC_SETTINGS));
    public static final Item DISC_018 = registerItem("disc_018", new mdpDiscs(14, musicDiscsPlusSE.DISC_018, DISC_SETTINGS));
    public static final Item DISC_019 = registerItem("disc_019", new mdpDiscs(14, musicDiscsPlusSE.DISC_019, DISC_SETTINGS));
    public static final Item DISC_020 = registerItem("disc_020", new mdpDiscs(14, musicDiscsPlusSE.DISC_020, DISC_SETTINGS));
    public static final Item DISC_021 = registerItem("disc_021", new mdpDiscs(14, musicDiscsPlusSE.DISC_021, DISC_SETTINGS));
    public static final Item DISC_022 = registerItem("disc_022", new mdpDiscs(14, musicDiscsPlusSE.DISC_022, DISC_SETTINGS));
    public static final Item DISC_023 = registerItem("disc_023", new mdpDiscs(14, musicDiscsPlusSE.DISC_023, DISC_SETTINGS));
    public static final Item DISC_024 = registerItem("disc_024", new mdpDiscs(14, musicDiscsPlusSE.DISC_024, DISC_SETTINGS));
    public static final Item DISC_025 = registerItem("disc_025", new mdpDiscs(14, musicDiscsPlusSE.DISC_025, DISC_SETTINGS));
    public static final Item DISC_026 = registerItem("disc_026", new mdpDiscs(14, musicDiscsPlusSE.DISC_026, DISC_SETTINGS));
    public static final Item DISC_027 = registerItem("disc_027", new mdpDiscs(14, musicDiscsPlusSE.DISC_027, DISC_SETTINGS));
    public static final Item DISC_028 = registerItem("disc_028", new mdpDiscs(14, musicDiscsPlusSE.DISC_028, DISC_SETTINGS));
    public static final Item DISC_029 = registerItem("disc_029", new mdpDiscs(14, musicDiscsPlusSE.DISC_029, DISC_SETTINGS));
    public static final Item DISC_030 = registerItem("disc_030", new mdpDiscs(14, musicDiscsPlusSE.DISC_030, DISC_SETTINGS));
    public static final Item DISC_031 = registerItem("disc_031", new mdpDiscs(14, musicDiscsPlusSE.DISC_031, DISC_SETTINGS));
    public static final Item DISC_032 = registerItem("disc_032", new mdpDiscs(14, musicDiscsPlusSE.DISC_032, DISC_SETTINGS));
    public static final Item DISC_033 = registerItem("disc_033", new mdpDiscs(14, musicDiscsPlusSE.DISC_033, DISC_SETTINGS));
    public static final Item DISC_034 = registerItem("disc_034", new mdpDiscs(14, musicDiscsPlusSE.DISC_034, DISC_SETTINGS));
    public static final Item DISC_035 = registerItem("disc_035", new mdpDiscs(14, musicDiscsPlusSE.DISC_035, DISC_SETTINGS));
    public static final Item DISC_036 = registerItem("disc_036", new mdpDiscs(14, musicDiscsPlusSE.DISC_036, DISC_SETTINGS));
    public static final Item DISC_037 = registerItem("disc_037", new mdpDiscs(14, musicDiscsPlusSE.DISC_037, DISC_SETTINGS));
    public static final Item DISC_038 = registerItem("disc_038", new mdpDiscs(14, musicDiscsPlusSE.DISC_038, DISC_SETTINGS));
    public static final Item DISC_039 = registerItem("disc_039", new mdpDiscs(14, musicDiscsPlusSE.DISC_039, DISC_SETTINGS));
    public static final Item DISC_040 = registerItem("disc_040", new mdpDiscs(14, musicDiscsPlusSE.DISC_040, DISC_SETTINGS));
    public static final Item DISC_041 = registerItem("disc_041", new mdpDiscs(14, musicDiscsPlusSE.DISC_041, DISC_SETTINGS));
    public static final Item DISC_042 = registerItem("disc_042", new mdpDiscs(14, musicDiscsPlusSE.DISC_042, DISC_SETTINGS));
    public static final Item DISC_043 = registerItem("disc_043", new mdpDiscs(14, musicDiscsPlusSE.DISC_043, DISC_SETTINGS));
    public static final Item DISC_044 = registerItem("disc_044", new mdpDiscs(14, musicDiscsPlusSE.DISC_044, DISC_SETTINGS));
    public static final Item DISC_045 = registerItem("disc_045", new mdpDiscs(14, musicDiscsPlusSE.DISC_045, DISC_SETTINGS));
    public static final Item DISC_046 = registerItem("disc_046", new mdpDiscs(14, musicDiscsPlusSE.DISC_046, DISC_SETTINGS));
    public static final Item DISC_047 = registerItem("disc_047", new mdpDiscs(14, musicDiscsPlusSE.DISC_047, DISC_SETTINGS));
    public static final Item DISC_048 = registerItem("disc_048", new mdpDiscs(14, musicDiscsPlusSE.DISC_048, DISC_SETTINGS));
    public static final Item DISC_049 = registerItem("disc_049", new mdpDiscs(14, musicDiscsPlusSE.DISC_049, DISC_SETTINGS));
    public static final Item DISC_050 = registerItem("disc_050", new mdpDiscs(14, musicDiscsPlusSE.DISC_050, DISC_SETTINGS));
    public static final Item DISC_051 = registerItem("disc_051", new mdpDiscs(14, musicDiscsPlusSE.DISC_051, DISC_SETTINGS));
    public static final Item DISC_052 = registerItem("disc_052", new mdpDiscs(14, musicDiscsPlusSE.DISC_052, DISC_SETTINGS));
    public static final Item DISC_053 = registerItem("disc_053", new mdpDiscs(14, musicDiscsPlusSE.DISC_053, DISC_SETTINGS));
    public static final Item DISC_054 = registerItem("disc_054", new mdpDiscs(14, musicDiscsPlusSE.DISC_054, DISC_SETTINGS));
    public static final Item DISC_055 = registerItem("disc_055", new mdpDiscs(14, musicDiscsPlusSE.DISC_055, DISC_SETTINGS));
    public static final Item DISC_056 = registerItem("disc_056", new mdpDiscs(14, musicDiscsPlusSE.DISC_056, DISC_SETTINGS));
    public static final Item DISC_057 = registerItem("disc_057", new mdpDiscs(14, musicDiscsPlusSE.DISC_057, DISC_SETTINGS));
    public static final Item DISC_058 = registerItem("disc_058", new mdpDiscs(14, musicDiscsPlusSE.DISC_058, DISC_SETTINGS));
    public static final Item DISC_059 = registerItem("disc_059", new mdpDiscs(14, musicDiscsPlusSE.DISC_059, DISC_SETTINGS));
    public static final Item DISC_060 = registerItem("disc_060", new mdpDiscs(14, musicDiscsPlusSE.DISC_060, DISC_SETTINGS));
    public static final Item DISC_061 = registerItem("disc_061", new mdpDiscs(14, musicDiscsPlusSE.DISC_061, DISC_SETTINGS));
    public static final Item DISC_062 = registerItem("disc_062", new mdpDiscs(14, musicDiscsPlusSE.DISC_062, DISC_SETTINGS));
    public static final Item DISC_063 = registerItem("disc_063", new mdpDiscs(14, musicDiscsPlusSE.DISC_063, DISC_SETTINGS));
    public static final Item DISC_064 = registerItem("disc_064", new mdpDiscs(14, musicDiscsPlusSE.DISC_064, DISC_SETTINGS));
    public static final Item DISC_065 = registerItem("disc_065", new mdpDiscs(14, musicDiscsPlusSE.DISC_065, DISC_SETTINGS));
    public static final Item DISC_066 = registerItem("disc_066", new mdpDiscs(14, musicDiscsPlusSE.DISC_066, DISC_SETTINGS));
    public static final Item DISC_067 = registerItem("disc_067", new mdpDiscs(14, musicDiscsPlusSE.DISC_067, DISC_SETTINGS));
    public static final Item DISC_068 = registerItem("disc_068", new mdpDiscs(14, musicDiscsPlusSE.DISC_068, DISC_SETTINGS));
    public static final Item DISC_069 = registerItem("disc_069", new mdpDiscs(14, musicDiscsPlusSE.DISC_069, DISC_SETTINGS));
    public static final Item DISC_070 = registerItem("disc_070", new mdpDiscs(14, musicDiscsPlusSE.DISC_070, DISC_SETTINGS));
    public static final Item DISC_071 = registerItem("disc_071", new mdpDiscs(14, musicDiscsPlusSE.DISC_071, DISC_SETTINGS));
    public static final Item DISC_072 = registerItem("disc_072", new mdpDiscs(14, musicDiscsPlusSE.DISC_072, DISC_SETTINGS));
    public static final Item DISC_073 = registerItem("disc_073", new mdpDiscs(14, musicDiscsPlusSE.DISC_073, DISC_SETTINGS));
    public static final Item DISC_074 = registerItem("disc_074", new mdpDiscs(14, musicDiscsPlusSE.DISC_074, DISC_SETTINGS));
    public static final Item DISC_075 = registerItem("disc_075", new mdpDiscs(14, musicDiscsPlusSE.DISC_075, DISC_SETTINGS));
    public static final Item DISC_076 = registerItem("disc_076", new mdpDiscs(14, musicDiscsPlusSE.DISC_076, DISC_SETTINGS));
    public static final Item DISC_077 = registerItem("disc_077", new mdpDiscs(14, musicDiscsPlusSE.DISC_077, DISC_SETTINGS));
    public static final Item DISC_078 = registerItem("disc_078", new mdpDiscs(14, musicDiscsPlusSE.DISC_078, DISC_SETTINGS));
    public static final Item DISC_079 = registerItem("disc_079", new mdpDiscs(14, musicDiscsPlusSE.DISC_079, DISC_SETTINGS));
    public static final Item DISC_080 = registerItem("disc_080", new mdpDiscs(14, musicDiscsPlusSE.DISC_080, DISC_SETTINGS));
    public static final Item DISC_081 = registerItem("disc_081", new mdpDiscs(14, musicDiscsPlusSE.DISC_081, DISC_SETTINGS));
    public static final Item DISC_082 = registerItem("disc_082", new mdpDiscs(14, musicDiscsPlusSE.DISC_082, DISC_SETTINGS));
    public static final Item DISC_083 = registerItem("disc_083", new mdpDiscs(14, musicDiscsPlusSE.DISC_083, DISC_SETTINGS));
    public static final Item DISC_084 = registerItem("disc_084", new mdpDiscs(14, musicDiscsPlusSE.DISC_084, DISC_SETTINGS));
    public static final Item DISC_085 = registerItem("disc_085", new mdpDiscs(14, musicDiscsPlusSE.DISC_085, DISC_SETTINGS));
    public static final Item DISC_086 = registerItem("disc_086", new mdpDiscs(14, musicDiscsPlusSE.DISC_086, DISC_SETTINGS));
    public static final Item DISC_087 = registerItem("disc_087", new mdpDiscs(14, musicDiscsPlusSE.DISC_087, DISC_SETTINGS));
    public static final Item DISC_088 = registerItem("disc_088", new mdpDiscs(14, musicDiscsPlusSE.DISC_088, DISC_SETTINGS));
    public static final Item DISC_089 = registerItem("disc_089", new mdpDiscs(14, musicDiscsPlusSE.DISC_089, DISC_SETTINGS));
    public static final Item DISC_090 = registerItem("disc_090", new mdpDiscs(14, musicDiscsPlusSE.DISC_090, DISC_SETTINGS));
    public static final Item DISC_091 = registerItem("disc_091", new mdpDiscs(14, musicDiscsPlusSE.DISC_091, DISC_SETTINGS));
    public static final Item DISC_092 = registerItem("disc_092", new mdpDiscs(14, musicDiscsPlusSE.DISC_092, DISC_SETTINGS));
    public static final Item DISC_093 = registerItem("disc_093", new mdpDiscs(14, musicDiscsPlusSE.DISC_093, DISC_SETTINGS));
    public static final Item DISC_094 = registerItem("disc_094", new mdpDiscs(14, musicDiscsPlusSE.DISC_094, DISC_SETTINGS));
    public static final Item DISC_095 = registerItem("disc_095", new mdpDiscs(14, musicDiscsPlusSE.DISC_095, DISC_SETTINGS));
    public static final Item DISC_096 = registerItem("disc_096", new mdpDiscs(14, musicDiscsPlusSE.DISC_096, DISC_SETTINGS));
    public static final Item DISC_097 = registerItem("disc_097", new mdpDiscs(14, musicDiscsPlusSE.DISC_097, DISC_SETTINGS));
    public static final Item DISC_098 = registerItem("disc_098", new mdpDiscs(14, musicDiscsPlusSE.DISC_098, DISC_SETTINGS));
    public static final Item DISC_099 = registerItem("disc_099", new mdpDiscs(14, musicDiscsPlusSE.DISC_099, DISC_SETTINGS));
    public static final Item DISC_100 = registerItem("disc_100", new mdpDiscs(14, musicDiscsPlusSE.DISC_100, DISC_SETTINGS));
    public static final Item DISC_101 = registerItem("disc_101", new mdpDiscs(14, musicDiscsPlusSE.DISC_101, DISC_SETTINGS));
    public static final Item DISC_102 = registerItem("disc_102", new mdpDiscs(14, musicDiscsPlusSE.DISC_102, DISC_SETTINGS));
    public static final Item DISC_103 = registerItem("disc_103", new mdpDiscs(14, musicDiscsPlusSE.DISC_103, DISC_SETTINGS));
    public static final Item DISC_104 = registerItem("disc_104", new mdpDiscs(14, musicDiscsPlusSE.DISC_104, DISC_SETTINGS));
    public static final Item DISC_105 = registerItem("disc_105", new mdpDiscs(14, musicDiscsPlusSE.DISC_105, DISC_SETTINGS));
    public static final Item DISC_106 = registerItem("disc_106", new mdpDiscs(14, musicDiscsPlusSE.DISC_106, DISC_SETTINGS));
    public static final Item DISC_107 = registerItem("disc_107", new mdpDiscs(14, musicDiscsPlusSE.DISC_107, DISC_SETTINGS));
    public static final Item DISC_108 = registerItem("disc_108", new mdpDiscs(14, musicDiscsPlusSE.DISC_108, DISC_SETTINGS));
    public static final Item DISC_109 = registerItem("disc_109", new mdpDiscs(14, musicDiscsPlusSE.DISC_109, DISC_SETTINGS));
    public static final Item DISC_110 = registerItem("disc_110", new mdpDiscs(14, musicDiscsPlusSE.DISC_110, DISC_SETTINGS));
    public static final Item DISC_111 = registerItem("disc_111", new mdpDiscs(14, musicDiscsPlusSE.DISC_111, DISC_SETTINGS));
    public static final Item DISC_112 = registerItem("disc_112", new mdpDiscs(14, musicDiscsPlusSE.DISC_112, DISC_SETTINGS));
    public static final Item DISC_113 = registerItem("disc_113", new mdpDiscs(14, musicDiscsPlusSE.DISC_113, DISC_SETTINGS));
    public static final Item DISC_114 = registerItem("disc_114", new mdpDiscs(14, musicDiscsPlusSE.DISC_114, DISC_SETTINGS));
    public static final Item DISC_115 = registerItem("disc_115", new mdpDiscs(14, musicDiscsPlusSE.DISC_115, DISC_SETTINGS));
    public static final Item DISC_116 = registerItem("disc_116", new mdpDiscs(14, musicDiscsPlusSE.DISC_116, DISC_SETTINGS));
    public static final Item DISC_117 = registerItem("disc_117", new mdpDiscs(14, musicDiscsPlusSE.DISC_117, DISC_SETTINGS));
    public static final Item DISC_118 = registerItem("disc_118", new mdpDiscs(14, musicDiscsPlusSE.DISC_118, DISC_SETTINGS));
    public static final Item DISC_119 = registerItem("disc_119", new mdpDiscs(14, musicDiscsPlusSE.DISC_119, DISC_SETTINGS));
    public static final Item DISC_120 = registerItem("disc_120", new mdpDiscs(14, musicDiscsPlusSE.DISC_120, DISC_SETTINGS));
    public static final Item DISC_121 = registerItem("disc_121", new mdpDiscs(14, musicDiscsPlusSE.DISC_121, DISC_SETTINGS));
    public static final Item DISC_122 = registerItem("disc_122", new mdpDiscs(14, musicDiscsPlusSE.DISC_122, DISC_SETTINGS));
    public static final Item DISC_123 = registerItem("disc_123", new mdpDiscs(14, musicDiscsPlusSE.DISC_123, DISC_SETTINGS));
    public static final Item DISC_124 = registerItem("disc_124", new mdpDiscs(14, musicDiscsPlusSE.DISC_124, DISC_SETTINGS));
    public static final Item DISC_125 = registerItem("disc_125", new mdpDiscs(14, musicDiscsPlusSE.DISC_125, DISC_SETTINGS));
    public static final Item DISC_126 = registerItem("disc_126", new mdpDiscs(14, musicDiscsPlusSE.DISC_126, DISC_SETTINGS));
    public static final Item DISC_127 = registerItem("disc_127", new mdpDiscs(14, musicDiscsPlusSE.DISC_127, DISC_SETTINGS));
    public static final Item DISC_128 = registerItem("disc_128", new mdpDiscs(14, musicDiscsPlusSE.DISC_128, DISC_SETTINGS));
    public static final Item DISC_129 = registerItem("disc_129", new mdpDiscs(14, musicDiscsPlusSE.DISC_129, DISC_SETTINGS));
    public static final Item DISC_130 = registerItem("disc_130", new mdpDiscs(14, musicDiscsPlusSE.DISC_130, DISC_SETTINGS));
    public static final Item DISC_131 = registerItem("disc_131", new mdpDiscs(14, musicDiscsPlusSE.DISC_131, DISC_SETTINGS));
    public static final Item DISC_132 = registerItem("disc_132", new mdpDiscs(14, musicDiscsPlusSE.DISC_132, DISC_SETTINGS));
    public static final Item DISC_133 = registerItem("disc_133", new mdpDiscs(14, musicDiscsPlusSE.DISC_133, DISC_SETTINGS));
    public static final Item DISC_134 = registerItem("disc_134", new mdpDiscs(14, musicDiscsPlusSE.DISC_134, DISC_SETTINGS));
    public static final Item DISC_135 = registerItem("disc_135", new mdpDiscs(14, musicDiscsPlusSE.DISC_135, DISC_SETTINGS));
    public static final Item DISC_136 = registerItem("disc_136", new mdpDiscs(14, musicDiscsPlusSE.DISC_136, DISC_SETTINGS));
    public static final Item DISC_137 = registerItem("disc_137", new mdpDiscs(14, musicDiscsPlusSE.DISC_137, DISC_SETTINGS));
    public static final Item DISC_138 = registerItem("disc_138", new mdpDiscs(14, musicDiscsPlusSE.DISC_138, DISC_SETTINGS));
    public static final Item DISC_139 = registerItem("disc_139", new mdpDiscs(14, musicDiscsPlusSE.DISC_139, DISC_SETTINGS));
    public static final Item DISC_140 = registerItem("disc_140", new mdpDiscs(14, musicDiscsPlusSE.DISC_140, DISC_SETTINGS));
    public static final Item DISC_141 = registerItem("disc_141", new mdpDiscs(14, musicDiscsPlusSE.DISC_141, DISC_SETTINGS));
    public static final Item DISC_142 = registerItem("disc_142", new mdpDiscs(14, musicDiscsPlusSE.DISC_142, DISC_SETTINGS));
    public static final Item DISC_143 = registerItem("disc_143", new mdpDiscs(14, musicDiscsPlusSE.DISC_143, DISC_SETTINGS));
    public static final Item DISC_144 = registerItem("disc_144", new mdpDiscs(14, musicDiscsPlusSE.DISC_144, DISC_SETTINGS));

    public static Item registerItem(String name, Item item) {
        return Registry.register(Registry.ITEM, new Identifier(MusicDiscsPlus.MOD_ID, name), item);
    }


    public static void registerItem() {
        MusicDiscsPlus.LOGGER.info("Registering Mod Items for " + MusicDiscsPlus.MOD_ID);
    }
}
